#!/bin/bash
set -e

stamp=$(date +%Y%m%d_%H%M%S)

if [ ! -f "Output" ]; then
	make testOpen
fi

out="results/massif.out.$(basename $1)-$stamp"

valgrind --tool=massif --massif-out-file=$out ./testOpen < $1

ms_print $out
